"""added user_id for tasks

Revision ID: cf0753ed3198
Revises: cb939bbc46e0
Create Date: 2024-07-25 22:28:02.366871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import db


# revision identifiers, used by Alembic.
revision: str = 'cf0753ed3198'
down_revision: Union[str, None] = 'cb939bbc46e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', db.schemas.GUID(), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_user_id_users'), 'tasks', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_user_id_users'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
