"""updated auth_users table

Revision ID: 533b29571ba5
Revises: a82d8d5c7ab1
Create Date: 2024-07-18 14:15:36.358356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533b29571ba5'
down_revision: Union[str, None] = 'a82d8d5c7ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('auth_users', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('auth_users', 'last_name')
    op.drop_column('auth_users', 'first_name')
    # ### end Alembic commands ###
