"""comment

Revision ID: ac757baf4ae8
Revises: 
Create Date: 2024-06-30 00:20:23.401353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.schemas import GUID

# revision identifiers, used by Alembic.
revision: str = 'ac757baf4ae8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('user_id', GUID(), nullable=False),
                    sa.Column('first_name', sa.String(length=64), nullable=False),
                    sa.Column('last_name', sa.String(length=64), nullable=True),
                    sa.Column('phone_number', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('user_id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
