"""Added new table

Revision ID: af07da6a5f6a
Revises: 56932c7f0e40
Create Date: 2024-07-09 22:11:14.258613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'af07da6a5f6a'
down_revision: Union[str, None] = '56932c7f0e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
                    sa.Column('auth_id', application.db.schemas.GUID(), nullable=False),
                    sa.Column('phone_number', sa.String(), nullable=False),
                    sa.Column('identity_number', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('auth_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_users')
    # ### end Alembic commands ###
